/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;
import igu.ventas.*;
/**
 *
 * @author tinov
 */
public class AdministradorHome extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorHome
     */
    public AdministradorHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        crearTorneo = new javax.swing.JMenuItem();
        revisarTorneo = new javax.swing.JMenuItem();
        terminarTorneo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        agregarUsuario = new javax.swing.JMenuItem();
        expulsarParticipante = new javax.swing.JMenuItem();
        editarPartipane = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu2.setText("Torneos");

        crearTorneo.setText("Crear Torneo");
        crearTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTorneoActionPerformed(evt);
            }
        });
        jMenu2.add(crearTorneo);

        revisarTorneo.setText("Revisar Torneos Actuales");
        revisarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisarTorneoActionPerformed(evt);
            }
        });
        jMenu2.add(revisarTorneo);

        terminarTorneo.setText("Terminar Torneo");
        jMenu2.add(terminarTorneo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administracion");

        agregarUsuario.setText("Agregar Particante");
        agregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(agregarUsuario);

        expulsarParticipante.setText("Expulsar Participante");
        expulsarParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expulsarParticipanteActionPerformed(evt);
            }
        });
        jMenu3.add(expulsarParticipante);

        editarPartipane.setText("Editar Participante");
        jMenu3.add(editarPartipane);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTorneoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearTorneoActionPerformed

    private void agregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarUsuarioActionPerformed
       CargaUser user = new CargaUser();
       user.setVisible(true);
    }//GEN-LAST:event_agregarUsuarioActionPerformed

    private void expulsarParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expulsarParticipanteActionPerformed
        ExpulsarUser user = new ExpulsarUser();
        user.setVisible(true);
    }//GEN-LAST:event_expulsarParticipanteActionPerformed

    private void revisarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisarTorneoActionPerformed
        ListaTorneos torneo = new ListaTorneos();
        torneo.setVisible(true);
    }//GEN-LAST:event_revisarTorneoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregarUsuario;
    private javax.swing.JMenuItem crearTorneo;
    private javax.swing.JMenuItem editarPartipane;
    private javax.swing.JMenuItem expulsarParticipante;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem revisarTorneo;
    private javax.swing.JMenuItem terminarTorneo;
    // End of variables declaration//GEN-END:variables
}
