/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author tinov
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelRegisUser = new javax.swing.JPanel();
        TxtEmail = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        jlabelRegistro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnRegis = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        ContraseñaUser = new javax.swing.JPasswordField();
        RegisAdm = new javax.swing.JPanel();
        txtClaveAdmin = new javax.swing.JTextField();
        txtUser1 = new javax.swing.JTextField();
        jlabelRegistro1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        btnRegis1 = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        jLabelClaveAdm = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));

        jPanelRegisUser.setBackground(new java.awt.Color(51, 51, 51));
        jPanelRegisUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailActionPerformed(evt);
            }
        });
        jPanelRegisUser.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 238, 121, -1));

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanelRegisUser.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 128, 121, -1));

        jlabelRegistro.setText("REGISTRO");
        jPanelRegisUser.add(jlabelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 16, -1, -1));

        jLabel2.setText("ingresar usuario");
        jPanelRegisUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 100, -1, -1));

        jLabel3.setText("ingresar contrasena");
        jPanelRegisUser.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 154, -1, -1));

        jLabel4.setText("ingresar email");
        jPanelRegisUser.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 210, -1, -1));

        jLabel6.setText("ingresar nombre");
        jPanelRegisUser.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 50, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanelRegisUser.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 72, 121, -1));

        btnRegis.setText("Registrarse");
        btnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisActionPerformed(evt);
            }
        });
        jPanelRegisUser.add(btnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 278, -1, -1));

        btnExit.setText("Atras");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanelRegisUser.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 334, -1, -1));

        ContraseñaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaUserActionPerformed(evt);
            }
        });
        jPanelRegisUser.add(ContraseñaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 176, 121, -1));

        jTabbedPane1.addTab("User", jPanelRegisUser);

        RegisAdm.setBackground(new java.awt.Color(51, 51, 51));
        RegisAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtClaveAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveAdminActionPerformed(evt);
            }
        });
        RegisAdm.add(txtClaveAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 290, 121, -1));

        txtUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUser1ActionPerformed(evt);
            }
        });
        RegisAdm.add(txtUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 128, 121, -1));

        jlabelRegistro1.setText("REGISTRO");
        RegisAdm.add(jlabelRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 16, -1, -1));

        jLabel5.setText("ingresar usuario");
        RegisAdm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 100, -1, -1));

        jLabel7.setText("ingresar contrasena");
        RegisAdm.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 154, -1, -1));

        jLabel8.setText("ingresar email");
        RegisAdm.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 210, -1, -1));

        jLabel9.setText("ingresar nombre");
        RegisAdm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 50, -1, -1));

        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });
        RegisAdm.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 72, 121, -1));

        btnRegis1.setText("Registrarse");
        btnRegis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegis1ActionPerformed(evt);
            }
        });
        RegisAdm.add(btnRegis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 324, -1, -1));

        btnExit1.setText("Atras");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        RegisAdm.add(btnExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 359, -1, -1));

        jLabelClaveAdm.setText("Ingresar clave Adm");
        RegisAdm.add(jLabelClaveAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 266, 96, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        RegisAdm.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 238, 121, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        RegisAdm.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 176, 121, -1));

        jTabbedPane1.addTab("Admin", RegisAdm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtClaveAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveAdminActionPerformed

    private void txtUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser1ActionPerformed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void btnRegis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegis1ActionPerformed
        // TODO add your handling code here:
        String claveAdmin = txtClaveAdmin.getText();
        String usuario = txtUser.getText();
        String password = txtPassword.getText();
        String email = txtEmail.getText();
        if(claveAdmin=="00229933"){
            
        }
    }//GEN-LAST:event_btnRegis1ActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void ContraseñaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaUserActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ContraseñaUser;
    private javax.swing.JPanel RegisAdm;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnRegis;
    private javax.swing.JButton btnRegis1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClaveAdm;
    private javax.swing.JPanel jPanelRegisUser;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlabelRegistro;
    private javax.swing.JLabel jlabelRegistro1;
    private javax.swing.JTextField txtClaveAdmin;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUser1;
    // End of variables declaration//GEN-END:variables

    private static class txtPassword {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public txtPassword() {
        }
    }
}
